### ISSUE TITLE
Can't sort fields without including GridFieldOrderableRows class

### ISSUE THREAD

**Issue by mandrew** [burnbright/silverstripe-sociallinks#1]
Suggest installing silverstripe-gridfieldextensions to get ordering working as it isn't clear that GridFieldOrderableRows is needed when installing using composer.

Also the 'Rows' field is hidden by default in the CMS so I can't really order the rows manually without including the silverstripe-gridfieldextensions module anyway so I guess requiring the module is a better way around this?

**Comment by jedateach** [comment]
Yeah man. I sense a pull request on its way! :smile:
